name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GODOT_VERSION: 4.6.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Godot imports
        uses: actions/cache@v4
        with:
          path: |
            .godot
            .import
          key: godot-${{ hashFiles('project.godot') }}
          restore-keys: |
            godot-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip openjdk-17-jdk

      - name: Download Godot
        run: |
          wget -q \
          https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}_stable_linux.x86_64.zip \
          -O godot.zip

          unzip -q godot.zip

          mv Godot_v${GODOT_VERSION}_stable_linux.x86_64 godot
          chmod +x godot

      - name: Install Export Templates
        run: |
          wget -q \
          https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}_stable_export_templates.tpz \
          -O templates.tpz

          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

          unzip -q templates.tpz \
            -d ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Verify export preset
        run: |
          if [ ! -f export_presets.cfg ]; then
            echo "export_presets.cfg not found!"
            exit 1
          fi

      - name: Create build directory
        run: mkdir -p build/android

      - name: Export APK
        run: |
          ./godot \
            --headless \
            --path . \
            --export-debug "Android" \
            build/android/app.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: build/android/app.apk
          
      # Tự động dọn dẹp Workflows Runs 【 5 Runs 】
      - name: ♻️𝐎𝐋𝐃 𝐖𝐎𝐑𝐊𝐅𝐋𝐎𝐖𝐒
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
            --paginate \
            --jq '.workflow_runs | sort_by(.created_at) | reverse | .[1:] | map(select(.status=="completed")) | .[].id' \
            | while read run; do
                echo "🗑️ đã xóa $run"
                gh api repos/${{ github.repository }}/actions/runs/$run -X DELETE
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_RESOURCES }}

      - name: ♻️𝐎𝐋𝐃 𝐂𝐀𝐂𝐇𝐄
        run: |
          gh cache list --json id,createdAt \
            | jq 'sort_by(.createdAt) | reverse | .[1:] | .[].id' \
            | while read id; do
                echo "🗑️ đã xóa $id"
                gh cache delete "$id"
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_RESOURCES }}
